import Head from 'next/head';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { config, dom } from '@fortawesome/fontawesome-svg-core';
import Header from '../src/components/generic/Header';
import Separator from '../src/components/generic/Separator';
import Waitlist from '../src/components/landing/Waitlist';
import FeatureGrid from '../src/components/landing/FeatureGrid';
import FeatureSection from '../src/components/landing/FeatureSection';
import HowItWorks from '../src/components/landing/HowItWorks';
import Pricing from '../src/components/landing/Pricing';
import FAQ from '../src/components/landing/FAQ';
import CTA from '../src/components/landing/CTA';
import Footer from '../src/components/generic/Footer';
import AOS from 'aos';
import 'aos/dist/aos.css';
import {
  Link,
  Button,
  Element,
  Events,
  animateScroll as scroll,
  scrollSpy,
  scroller,
} from 'react-scroll';
import ApartmentRoom from '../public/dan-gold-4HG3Ca3EzWw-unsplash.jpg';
import ModernBedroom from '../public/sidekix-media-WDUtNbot6Qw-unsplash.jpg';
import ModernLivingRoom from '../public/livingroom-g6e854ffa2_1280.jpg';

export default function Home() {
  useEffect(() => {
    AOS.init({
      offset: 200,
      duration: 750,
    });
  }, []);

  return (
    <div>
      <Head>
        <title>LifeWay</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <style>{dom.css()}</style>
      </Head>
      <main className='bg-white'>
        <Header />
        <div
          data-aos='fade-up'
          className='px-4 bg-gradient-to-b from-white to-primary'
        >
          <div className='max-w-2xl pt-32 m-auto text-center md:pt-40'>
            <h1 className='mb-16 text-6xl font-bold md:text-7xl text-midnight-blue'>
              Experience the Perfect Blend of Style and Comfort at
              <span className='text-transparent bg-clip-text bg-gradient-to-r from-sky-400 to-primary'>
                {` LifeWay`}
              </span>
            </h1>
            <p className='my-8 text-2xl font-medium text-gray-600'>
              Step Into the Future of Apartment Living with Our Smart Home
              Technology
            </p>
            <Waitlist />
          </div>
          <Image
            className='max-w-6xl m-auto mt-20 rounded-lg h-96 md:flex'
            src={ApartmentRoom}
            alt='Picture of apartment'
            // width={1000}
            // height={500}
          />
          {/* <div className='max-w-6xl m-auto mt-20 rounded-t-lg h-96 bg-midnight-blue'></div> */}
          {/* <div className='max-w-6xl m-auto rounded-b-lg h-96 bg-midnight-blue md:mb-20'></div> */}
          <div className='max-w-2xl py-16 m-auto' data-aos='fade-up'>
            <h2 className='mt-4 text-5xl font-bold text-center text-white md:text-6xl'>
              Our latest complex:
            </h2>
            <h2 className='mt-4 text-5xl font-bold text-center text-transparent bg-clip-text md:text-6xl bg-gradient-to-r from-sky-400 to-primary'>
              The Grand
            </h2>
            <p className='my-8 text-2xl font-medium text-center text-white'>
              A whole new way to rent in the heart of the cities you love. From
              fully furnished studios, 1 bed, 2 bed and 3 bed apartments to the
              penthouse collection, there is something for everyone with a
              LifeWay new build apartment.
            </p>
            <div className='justify-between m-auto md:flex'>
              <div className='py-2 mb-8 text-center md:mb-0'>
                <h2 className='mb-2 text-5xl font-bold md:text-6xl'>196</h2>
                <p className='text-2xl font-medium'>Properties</p>
              </div>
              <div className='py-2 mb-8 text-center md:mb-0'>
                <h2 className='mb-2 text-5xl font-bold md:text-6xl'>24/7</h2>
                <p className='text-2xl font-medium'>Conceirge</p>
              </div>
              <div className='py-2 text-center'>
                <h2 className='mb-2 text-5xl font-bold md:text-6xl'>
                  Exclusive
                </h2>
                <p className='text-2xl font-medium'>interior design</p>
              </div>
            </div>
          </div>
        </div>

        <div className='py-8 mt-8 md:py-16 md:mt-16' data-aos='fade-up'>
          <HowItWorks
            title='Amenities'
            subtitle='24/7 residents gym,Wellness workshops, Move-in health checks, Mental Health First Aiders, 250MBPS broadband, 24-hour concierge, On-site maintenance, Security - CCTV secure by design, Samsung appliances, Outside gardens Roof terraces, Cinema, games room, Flexible workspace, Shared lounges & library, Resident dining space, Resident events & clubs, Bicycle storage & maintenance, the list goes on.....'
          />
        </div>

        <div
          className='py-8 bg-gradient-to-b from-white to-primary'
          data-aos='fade-up'
        >
          <div className='max-w-2xl py-16 m-auto'>
            <h2 className='mt-4 text-5xl font-bold text-center text-midnight-blue md:text-6xl'>
              LifeWay Apartments: Where Residents Come First.
            </h2>
            <p className='mt-8 text-2xl font-medium text-center text-gray-600'>
              Hear From Our Satisfied Tenants.
            </p>
          </div>
        </div>
        <div className='px-4 overflow-hidden'>
          <FeatureSection
            title='The Oasis'
            // subtitle='Quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora'
            quote='The Oasis is a true gem in the heart of the city. The stunning architecture, expansive views, and high-end finishes make it the perfect place for anyone looking for a luxurious living experience.'
            name='Maria Rodriguez'
            side='left'
            image={
              <Image
                src={ModernBedroom}
                alt='Picture of Bedroom'
                className='rounded-lg md:flex-1'
                height={250}
                width={450}
              />
            }
          />
        </div>
        <div className='px-4 mt-8 overflow-hidden md:mt-16'>
          <FeatureSection
            title='Harmony Heights'
            // subtitle='Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.'
            quote="Harmony Heights is more than just an apartment complex, it's a community. The staff goes above and beyond to make residents feel welcome and comfortable, and the events and activities organized by the community create a real sense of belonging."
            name='Jameson Lee'
            side='right'
            image={
              <Image
                src={ModernLivingRoom}
                alt='Picture of Bedroom'
                className='rounded-lg md:flex-1'
                height={250}
                width={450}
              />
            }
          />
        </div>
        <div className='py-8 md:py-16' data-aos='fade-up'>
          <Pricing
            title='Pricing plans for Apartments'
            // subtitle='Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam'
            onClick={scroll.scrollToTop}
          />
        </div>
        {/* <div className='px-4 py-8 md:py-16' data-aos='fade-up'>
          <FAQ />
        </div> */}
        <div
          className='px-4 py-8 md:py-16'
          data-aos='fade-up'
          onClick={() => scroll.scrollToTop()}
        >
          <CTA
            title='Ready to move in?'
            // subtitle='ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur'
            onCTAClick={scroll.scrollToTop}
          />
        </div>
        <Footer />
      </main>
    </div>
  );
}
